-- Tables pour NEVUS AFRICA sur Supabase

-- 1. Paramètres du site
CREATE TABLE site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Sections de contenu
CREATE TABLE sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  title TEXT,
  content TEXT,
  order_index INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Informations de contact
CREATE TABLE contact_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT UNIQUE NOT NULL,
  value TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Messages de contact
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT,
  subject TEXT,
  content TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Utilisateurs Admin
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL, -- Hash bcrypt
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Données par défaut (Initialisation)
INSERT INTO site_settings (key, value) VALUES 
('primary_color', '#1A2B3C'),
('secondary_color', '#2C3E50'),
('accent_color', '#D35400'),
('text_color', '#2C3E50'),
('button_color', '#D35400'),
('button_hover_color', '#A04000')
ON CONFLICT (key) DO NOTHING;

INSERT INTO sections (name, title, content, order_index) VALUES 
('hero', 'Inclusion & Excellence Médicale', 'Inclusion sociale, médicale et humaine des personnes vivant avec des naevus congénitaux géants en Afrique.', 1),
('about', 'Notre Combat', 'Fondée par Mardochée NGATSE, porteur de NCG, NEVUS AFRICA œuvre pour briser l''isolement des familles et promouvoir une approche unifiée de la recherche et des soins.', 2),
('missions', 'Nos Missions', 'Améliorer la qualité de vie, renforcer la visibilité, faciliter l''accès à l''information médicale...', 3),
('programs', 'Nos Programmes', 'Sensibilisation & Éducation, Accompagnement & Soutien, Recherche & Innovation Médicale...', 4)
ON CONFLICT (name) DO NOTHING;

INSERT INTO contact_info (type, value) VALUES 
('email', 'contact@nevusafrica.org'),
('phone', '+242 06 650 52 90'),
('address', 'Pointe-Noire, République du Congo')
ON CONFLICT (type) DO NOTHING;

-- Création de l'utilisateur admin par défaut
-- admin / root@2020
INSERT INTO users (username, password) 
VALUES ('admin', '$2b$10$pFQj8br3PSub477kimFp8uwXOzFJag18vKieaiNuiMajUNPjo4oCW')
ON CONFLICT (username) DO NOTHING;
